[package]
name = "sandcrate-backend"
edition = "2021"

[dependencies]
wasmtime = "15"
wasmtime-wasi = "15"
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }